# Multiple Linear Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import mean_squared_error

## Importing the dataset

In [2]:
df = pd.read_csv('50_Startups.csv')
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
# Correct way to filter for numeric columns
df = df.select_dtypes(include=['number'])

In [4]:
df.head()

   R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [5]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [6]:


#Correlation Matrix
cor = df.corr()
print(cor)

                 R&D Spend  Administration  Marketing Spend    Profit
R&D Spend         1.000000        0.241955         0.724248  0.972900
Administration    0.241955        1.000000        -0.032154  0.200717
Marketing Spend   0.724248       -0.032154         1.000000  0.747766
Profit            0.972900        0.200717         0.747766  1.000000

In [7]:
print(X)

[[165349.2  136897.8  471784.1 ]
 [162597.7  151377.59 443898.53]
 [153441.51 101145.55 407934.54]
 [144372.41 118671.85 383199.62]
 [142107.34  91391.77 366168.42]
 [131876.9   99814.71 362861.36]
 [134615.46 147198.87 127716.82]
 [130298.13 145530.06 323876.68]
 [120542.52 148718.95 311613.29]
 [123334.88 108679.17 304981.62]
 [101913.08 110594.11 229160.95]
 [100671.96  91790.61 249744.55]
 [ 93863.75 127320.38 249839.44]
 [ 91992.39 135495.07 252664.93]
 [119943.24 156547.42 256512.92]
 [114523.61 122616.84 261776.23]
 [ 78013.11 121597.55 264346.06]
 [ 94657.16 145077.58 282574.31]
 [ 91749.16 114175.79 294919.57]
 [ 86419.7  153514.11      0.  ]
 [ 76253.86 113867.3  298664.47]
 [ 78389.47 153773.43 299737.29]
 [ 73994.56 122782.75 303319.26]
 [ 67532.53 105751.03 304768.73]
 [ 77044.01  99281.34 140574.81]
 [ 64664.71 139553.16 137962.62]
 [ 75328.87 144135.98 134050.07]
 [ 72107.6  127864.55 353183.81]
 [ 66051.52 182645.56 118148.2 ]
 [ 65605.48 153032.06 107138.38]
 [ 61994.48 115641.28  91131.24]
 [ 61136.38 152701.92  88218.23]
 [ 63408.86 129219.61  46085.25]
 [ 55493.95 103057.49 214634.81]
 [ 46426.07 157693.92 210797.67]
 [ 46014.02  85047.44 205517.64]
 [ 28663.76 127056.21 201126.82]
 [ 44069.95  51283.14 197029.42]
 [ 20229.59  65947.93 185265.1 ]
 [ 38558.51  82982.09 174999.3 ]
 [ 28754.33 118546.05 172795.67]
 [ 27892.92  84710.77 164470.71]
 [ 23640.93  96189.63 148001.11]
 [ 15505.73 127382.3   35534.17]
 [ 22177.74 154806.14  28334.72]
 [  1000.23 124153.04   1903.93]
 [  1315.46 115816.21 297114.46]
 [     0.   135426.92      0.  ]
 [   542.05  51743.15      0.  ]
 [     0.   116983.8   45173.06]]

## Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [9]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [10]:
# Calculate and print RMSE for training set
print("Regression")
print("====================")
y_pred_train = regressor.predict(X_train)
RMSE_train = np.sqrt(mean_squared_error(y_train, y_pred_train))
print("Regression Train set: RMSE {}".format(RMSE_train))

# Predict and evaluate on the testing set
y_pred = regressor.predict(X_test)
RMSE_test = np.sqrt(mean_squared_error(y_test, y_pred))
print("====================")
print("Regression Test set: RMSE {}".format(RMSE_test))

Regression
====================
Regression Train set: RMSE 9052.267248800474
====================
Regression Test set: RMSE 8803.775790469346

In [11]:
# Code for obtainging Model coefficients along with their relevant categories
feature_names = df.columns[:-1] # Gets R&D Spend, Administration, Marketing Spend
coef_dict = {}

for coef, feat in zip(regressor.coef_, feature_names):
    coef_dict[feat] = float(coef)  # <--- Cast to standard Python float here

print("Model Coefficients:")
print(coef_dict)

Model Coefficients:
{'R&D Spend': 0.7788410440821667, 'Administration': 0.02939189909755259, 'Marketing Spend': 0.0347102548694203}

In [12]:
mrd=regressor.coef_[0] #b1 which is Model Coefficient of R&D Spend

In [13]:
mad=regressor.coef_[1] #b2 which is Model Coefficient of Administration

In [14]:
mms=regressor.coef_[2]  #b3 which is Model Coefficient of Marketing Spend

In [15]:
c=regressor.intercept_ # b0 which is intercept

In [16]:
X_test[0] # first sample of test set

array([ 66051.52, 182645.56, 118148.2 ])

#**Verifying the prediction of first sample of test using equation of multiple linear regression**

#$$y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \dots + \beta_n x_n $$

In [17]:
float(X_test[0][0]*mrd + X_test[0][1]*mad + X_test[0][2]*mms + c)

103901.89696960004

#You can verify other samples of test set just by changing the index number of X_test

In [18]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[103901.9  103282.38]
 [132763.06 144259.4 ]
 [133567.9  146121.95]
 [ 72911.79  77798.83]
 [179627.93 191050.39]
 [115166.65 105008.31]
 [ 67113.58  81229.06]
 [ 98154.81  97483.56]
 [114756.12 110352.25]
 [169064.01 166187.94]]